added dropdownMenu Team on navbar, created Dev Team page
SCE-Development/Clark pull request #1131
Opened 2022-08-03 09:31 UTC by phuvu0107

2022-08-03 20:33 UTC, ekanshgupta123 commented
your frontend test is failing

2022-08-04 01:42 UTC, evanugarte commented
add test steps + screenshot

2022-08-04 03:40 UTC, neelp03 requested changes

2022-08-04 03:40 UTC, neelp03 commented on src/Components/Navbar/UserNavbar.js
> +                            className='authenticated-navlink'
delete this line and it should fix your tests

2022-08-07 19:48 UTC, neelp03 approved these changes

2024-01-03 08:23 UTC, closed without merging