Door code discord bot
SCE-Development/Clark pull request #1134
Opened 2022-08-04 22:02 UTC by fahmed0710

Core-v4 API to retrieve doorcodes based on user's discord ID

2022-08-04 22:18 UTC, neelp03 reviewed
There a bunch of random changes, most likely because of auto formatter
fyi, if you are using prettier with vscode in the settings.json of vscode, you can add this line:
```json
"prettier.singleQuote": true
```
so when you do auto format it keeps single quotes, similarly you can do
```json
  "trailingComma" : "none"
```
to avoid adding random commas when you do auto format, p sure there are also ways to avoid adding space before function parentheses when doing auto format

2022-08-04 22:28 UTC, neelp03 reviewed
No API tests?

2022-08-25 17:28 UTC, neelp03 requested changes
Merge conflicts and consider adding api tests

2022-08-26 00:25 UTC, ShaivPandya approved these changes

2024-07-23 21:12 UTC, closed without merging