User Manager Pagination
SCE-Development/Clark pull request #1135
Opened 2022-08-05 19:18 UTC by davidtanline

add pagination and UI changes to User Manager

2022-08-05 19:25 UTC, neelp03 requested changes

2022-08-05 19:25 UTC, neelp03 commented on api/main_endpoints/routes/User.js
> +    const search = req.query.search || '';
Change name and add token check back in

2022-08-05 19:25 UTC, neelp03 commented on populate.js
> +
We don't need this file anymore

2022-08-05 19:25 UTC, neelp03 commented on src/Components/Routing/PrivateRoute.js
> +// import { Route, Redirect } from 'react-router-dom';
uncomment all the stuff we need

2022-08-05 19:25 UTC, neelp03 commented on src/Routing.js
>        inAdminNavbar: true
ig we can delete this now

2022-08-05 19:25 UTC, neelp03 commented on src/index.js
> +// import { withRouter } from 'react-router-dom';
do we need this?

2022-08-05 19:25 UTC, neelp03 commented on src/Pages/Overview/Overview.js
>      return (
don't think we need this file anymore

2023-02-11 05:59 UTC, evanugarte reviewed
haven't forgotten about this, will be merged soon (by summer)

2023-11-07 08:50 UTC, evanugarte commented
closed by #1310

2023-11-07 08:50 UTC, closed without merging